deployments:
  deploymentGating:
    enabled: true
    retry: 50
    sleep: 30
    environments:
    - Development
    - Production
  services:
    ids:
    - b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlL2VhOWQwNmJhLTJmOTAtNDA1Yi05YTY0LWMwYTUyNDVkM2NkNS9iMDY5NTk1Mi01ZWVkLTExZjEtODk4Ni0wYWZmY2YwZmJkMDk=
